<?php

namespace App\Http\Controllers\Telegram;

use DefStudio\Telegraph\Handlers\WebhookHandler;
use Illuminate\Support\Facades\Log;
use App\Models\Telegram\User;
use Throwable;

class Handler extends WebhookHandler
{


    /**
     * @param string $text
     * @return void
     */
    public function hello(string $text): void
    {
        $this->reply("На курточке надпись $text");
    }

    /**
     * @param \Stringable $text
     * @return void
     */
    protected function handleUnknownCommand(\Stringable $text): void
    {
        if($text->value === "/start"){
            $this->reply("Трудное начало");
        } else {
            $this->reply("Не пойму, о чём речь");
        }
    }

    /**
     * @return void
     */
    public function start(): void
    {
        $userData = $this->message->chat();
        $addData = $this->message->from();
        $username = $userData->username();
        User::updateOrCreate([
            "tg_id"=> $userData->id(),
            'first_name' => $userData->firstname(),
            'last_name' => $userData->lastname(),
            'username' => $userData->username(),
            'language_code' => $addData->languageCode(),
            'is_premium' => $addData->isPremium(),
            'is_bot' => $addData->isBot(),
        ]);
        $this->reply("Привет, $username!");
    }

    /**
     * @param \Stringable $message
     * @return void
     */
    protected function handleChatMessage(\Stringable $message): void
    {
        Log::info(json_encode($this->message->toArray()));
    }


    /**
     * @return void
     */
    public function random(): void
    {
        $randomPhrase = collect(__('messages'))->random();
        $this->reply($randomPhrase);
    }

    /**
     * @return Void
     */
    public function end(): Void
    {
        $isDead = collect(__('end'))->random();
        $this->reply($isDead);
    }

    /**
     * @param Throwable $throwable
     * @return void
     * @throws Throwable
     */
    public function onFailure(Throwable $throwable): void
    {
        parent::onFailure($throwable); // TODO: Change the autogenerated stub
    }

}

